### ISSUE TITLE
Version 4.0.19 on NPM still has old built code 

### ISSUE THREAD

**Issue by JoelBesada** [ProjectOpenSea/opensea-js#867]
I'm trying to upgrade to version `4.0.19` where the following protocol address fix should be included https://github.com/ProjectOpenSea/opensea-js/pull/863. However, looking at the code in `node_modules/opensea-js/lib/utils/utils.js`, it doesn't have the expected `isValidProtocol` function at the bottom that this fix added.

## Steps to reproduce
Install opensea-js from NPM and look at the output in the utils file: 
```
$ mkdir test_folder && cd test_folder && yarn init
$ yarn add opensea-js
$ tail -n 2 node_modules/opensea-js/lib/utils/utils.js  
```
This prints 
```
exports.feesToBasisPoints = feesToBasisPoints;
//# sourceMappingURL=utils.js.map%  
```
while the expected output should be 
```
exports.isValidProtocol = isValidProtocol;
//# sourceMappingURL=utils.js.map%   
```

It seems that `yarn build` wasn't executed before publishing this new update to NPM.

**Comment by cterech** [comment]
thanks for reporting! fixed in 4.0.20

**Comment by JoelBesada** [comment]
> thanks for reporting! fixed in 4.0.20

Hey, I pulled down the latest version but still getting the same output, `isValidProtocol` is still not in the built output (it's in the file in the `src` folder but that's not what the library exposes when imported).
