### ISSUE TITLE
Sales not completing on Polygon Mumbai Testnet

### ISSUE THREAD

**Issue by rforzani** [ProjectOpenSea/opensea-js#942]
I am trying to complete a sale on opensea tesnet. I have published an ERC 1155 contract inheriting from OpenZeppelin's ERC1155Upgradeable implementation. I am able to successfully transfer the nft on Opensea as well as listing it for sale, but as soon as I try completing a purchase I get the error: 
Execution reverted. Please reach out to the collection owner to troubleshoot.
However there doesn't seem to be any issue with the smart contract code I have used as it passes all tests and also inherits from OpenZeppelin as said earlier. 
I the browser console I get the following error coming from Metamask: 
Error: Internal JSON-RPC error. (code: -32603, data: {"code":3,"message":"execution reverted","data":"0x93daadf200000000000000000000000000000000000000adc04c56bf30ac9d3c0aaf14dc"})

**Comment by QueryArtCodes** [comment]
Did you find the solution? I got the same problem with erc-721 contract.

**Comment by rforzani** [comment]
> Did you find the solution? I got the same problem with erc-721 contract.

No I'm sorry but I didn't find any solutions. The problem is almost certainly to do with a bug in Opensea's Mumbai testnet code. We can't do anything but test it on main net or change testnet until they investigate the issue. Good luck.

**Comment by hw711** [comment]
I have the same exact error with my NFT contract on Arbitrum Goerli.  Happens when trying to approve purchase.  Metamask wouldn't even pop up so maybe revert comes from Opensea calling a getter or something?  I wish there is a way to track this down.

**Comment by QueryArtCodes** [comment]
> 
This is the really weird issue. I believe it is totally on the OpenSea side.

I checked all collections with proved sales in MATIC, copied the simplest contract code and deployed it from my account. 
Made listing, set up the price and... All the same - purchase can not be finished because of "Execution reverted. Please reach out to the collection owner to troubleshoot." 
No other data to deal with. Just a console message: 
{code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
code
: 
-32603
data
: 
{code: 3, message: 'execution reverted', data: '0x93daadf200000000000000000000000000000000000000adc04c56bf30ac9d3c0aaf14dc'}
message
: 
"Internal JSON-RPC error.

Which does help much.

**Comment by ryanio** [comment]
We are looking into resolving it now, thanks for reporting

**Comment by ryanio** [comment]
This should be resolved now, can you try again?

**Comment by QueryArtCodes** [comment]
> This should be resolved now, can you try again?

Yeah! It worked at last!

Pretty quick reaction. Thanks for that.

Can I count on this error will not happen with other smart contracts on Mumbai?
As I have to test out more complicated ones.

**Comment by hw711** [comment]
Is the fix only for mumbai?  I still get the same error on Arbitrum goerli.  https://testnets.opensea.io/assets/arbitrum-goerli/0x01237b0c73b9542a425cd3b96d66e9c6b4e63dd2/1

**Comment by rforzani** [comment]
> Is the fix only for mumbai? I still get the same error on Arbitrum goerli. https://testnets.opensea.io/assets/arbitrum-goerli/0x01237b0c73b9542a425cd3b96d66e9c6b4e63dd2/1

I confirm the issue has been fixed for Mumbai. I'm not sure about Arbitrum Goerli though.
